# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CQzB2f0PXJLeKjnKX4wtgRZo3WXDAJZ4
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

bikes = pd.read_csv('london_merged.csv')
bikes.head()

bikes.shape

bikes.columns

new_names_col = {
    'timestamp': 'TimeStamp_Field',
    'cnt':'Coun_of_New_Bikes',
    't1' :'Real_Temp_C ',
    't2':'temp_Feels_Like_C',
    'hum': 'Humidity',
    'wind_speed': 'Wind_Speed_km/h ',
    'weather_code': 'Weather_code',
    'is_holiday': 'Is_Holiday',
    'is_weekend': 'Is_Weekend',
    'season': 'Season'
}
bikes.rename(columns=new_names_col, inplace=True)
bikes.head()

bikes['Humidity']= bikes['Humidity'].astype('str')+'%'
bikes

print(bikes['Season'].value_counts())

from re import S
Season_Dict = {'0.0':'Spring', '1.0':'Summer', '2.0':'Fall', '3.0':'Winter'}
bikes.Season = bikes.Season.astype('str')
bikes.Season = bikes.Season.map(Season_Dict)
bikes.head()

print(bikes['Is_Holiday'].value_counts())

isholiday_Dict = {'0.0':'N', '1.0':'Y'}
bikes.Is_Holiday = bikes.Is_Holiday.astype('str')
bikes.Is_Holiday = bikes.Is_Holiday.map(isholiday_Dict)
bikes.head()

print(bikes['Is_Holiday'].value_counts())

bikes.head()

print(bikes['Is_Weekend'].value_counts())

isweekend_dict = { '0.0':'N', '1.0':'Y'}
bikes.Is_Weekend = bikes.Is_Weekend.astype('str') #convert it into str
bikes.Is_Weekend = bikes.Is_Weekend.map(isweekend_dict)
bikes.head()

print(bikes['TimeStamp_Field'].value_counts)

bikes['TimeStamp_Field'] = pd.to_datetime(bikes['TimeStamp_Field'])
bikes.head()

print(bikes['Weather_code'].value_counts())

WeatherCode_dict = {
    '1.0'  :   'Clear',
     '2.0'  :   'Scattered Cloud',
     '3.0'   :  'broken Clouds',
     '7.0'  :   'cloudy',
     '4.0'  :  'rain',
     '26.0'  :   'rain with thunderstorm',
     '10.0'  :    'Snowfull'
}
bikes.Weather_code=bikes.Weather_code.astype('str')
bikes.Weather_code =bikes.Weather_code.map(WeatherCode_dict)
bikes.head()

#wrote the Final DataFrame to an excel file that we will use in our Tableau for viusalization.
bikes.to_excel('london_merged.csv.xlsx', sheet_name="DataCleaned")

